# Generated by Django 4.1 on 2023-09-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pharm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Syrup', 'Syrup'), ('Tablet', 'Tablet'), ('Injection', 'Injection'), ('Capsule', 'Capsule'), ('Caplet', 'Caplet'), ('Powder', 'Powder')], max_length=200)),
                ('maufacturer', models.CharField(max_length=150)),
                ('photo', models.FileField(max_length=500, upload_to='drugs')),
                ('description', models.CharField(max_length=500)),
                ('pharm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharm.pharmacy')),
            ],
        ),
    ]
