# Generated by Django 4.1 on 2023-09-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharm', '0003_drug_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='pharm_id',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='drugs',
            field=models.ManyToManyField(to='Pharm.drug'),
        ),
    ]
